"""Run a REAL candidate through the REAL admission contract and report what it actually fails.

WHY THIS EXISTS. `load_admission_contract` now refuses a contract whose thresholds contradict each
other, and `tests/unit/test_sleeve_admission.py` proves a hand-built evidence bundle can pass. Both
are abstract: the first checks arithmetic, the second checks a fixture written to succeed. Neither
answers the question that matters -- can anything REAL get through?

That distinction has bitten this project before: a fixture reaches states the product cannot. So
this measures the live book's own sleeves through the production `diversification_report`, builds
evidence from those measurements, and runs the production evaluator over it. Whatever it fails is
what a genuine candidate would fail.

CLAIM BOUNDARY. This registers NO hypothesis identity and tests no new idea. Every curve read here
belongs to an identity already recorded in the ledger; re-measuring an existing identity's
diversification against the book is admissibility MECHANICS, not a return hypothesis. It proposes
no sleeve and produces no verdict about any candidate's edge.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from alphaforge.portfolio.book import SleeveCurve, combine_book
from alphaforge.validation.diversification import diversification_report
from alphaforge.validation.sleeve_admission import (
    evaluate_sleeve_evidence,
    load_admission_contract,
)

REPO = Path(__file__).resolve().parents[1]
CONTRACT = REPO / "config" / "sleeve_admission_contract.json"
OUTPUT = REPO / "artifacts" / "analysis" / "admission_dry_run" / "result.json"

# The three traded sleeves, plus the fourth that carries a quarter of the book on a KILLED verdict.
# The same curve sources analyze_stressed_correlation.py uses, so this is comparable with the
# published correlation work rather than a second private convention. Their FRESHNESS is measured
# and reported, because two of them are research curves regenerated by hand and one is a
# live-forward curve regenerated daily -- a correlation measured across that mixture is bounded by
# the stalest member, and that bound belongs in the output rather than in someone's memory.
BOOK = {
    "AlphaForge": "artifacts/walkforward/crypto_carry_wk/equity.parquet",
    "AlphaMax": "artifacts/walkforward/k30_dn_63/equity.parquet",
    "AlphaTrend": "artifacts/walkforward/mf_live_fwd/equity.parquet",
}
# The candidate: a real, already-registered identity with a long published curve.
CANDIDATE = ("AlphaVintage (cpi_surprise_size)", "artifacts/probe/cpi_surprise_size/equity.parquet")

TRADING_DAYS = 252.0


def _returns(path: Path) -> pd.Series:
    frame = pd.read_parquet(path)
    series = pd.Series(
        frame["equity"].to_numpy(dtype=float),
        index=pd.to_datetime(frame["ts"], unit="ms", utc=True).dt.normalize(),
    )
    series = series[~series.index.duplicated(keep="last")].sort_index()
    return series.pct_change().dropna()


def main() -> int:
    contract = load_admission_contract(CONTRACT)

    frames = {}
    provenance: dict[str, dict[str, str]] = {}
    for name, rel in BOOK.items():
        path = REPO / rel
        if not path.exists():
            continue
        frames[name] = _returns(path)
        provenance[name] = {
            "path": rel,
            "last_observation": str(frames[name].index[-1].date()),
            "file_modified": dt.datetime.fromtimestamp(
                path.stat().st_mtime, tz=dt.UTC
            ).date().isoformat(),
            "kind": "blessed research curve, frozen by disclosure protocol"
            if name in {"AlphaForge", "AlphaMax"}
            else "live-forward curve, regenerated by the daily tick",
        }
    candidate_path = REPO / CANDIDATE[1]
    if not candidate_path.exists() or len(frames) < 2:
        print("insufficient real curves on disk; refusing to fabricate a dry run")
        return 1
    frames["__candidate__"] = _returns(candidate_path)

    # TWO DIFFERENT COUNTS, AND CONFLATING THEM IS THE MISTAKE.
    #   * The production combiner (alphaforge.portfolio.book.combine_book) aligns to a contiguous
    #     epoch-day index and treats an absent day as FLAT, which is what it is. That gives the
    #     window LENGTH -- 1061 days here.
    #   * A correlation can only be estimated from days on which both series are genuinely
    #     ACTIVE. That is the intersection, 728 days here, and it is what
    #     correlation_observations must mean.
    # An earlier revision of this script used pd.DataFrame(...).dropna() for both, which is the
    # calendar-alignment defect this repository already documented: it silently discarded 31% of
    # the window (every weekend for the 24/7 crypto sleeve, every equity holiday) and then
    # reported the survivor count as the window.
    production_window = combine_book(
        [
            SleeveCurve(
                name=name,
                ts_ms=[int(v) for v in pd.read_parquet(REPO / rel)["ts"].to_numpy()],
                equity=[float(v) for v in pd.read_parquet(REPO / rel)["equity"].to_numpy()],
            )
            for name, rel in BOOK.items()
            if (REPO / rel).exists()
        ],
        scheme="equal_risk",
    ).n_days

    aligned = pd.DataFrame(frames).dropna()
    if aligned.empty:
        print("no common window across the real curves")
        return 1
    candidate = aligned.pop("__candidate__")
    sleeves = {name: aligned[name].to_numpy() for name in aligned.columns}
    book = aligned.mean(axis=1).to_numpy()
    observations = len(candidate)

    # A predeclared stress mask, stated here rather than discovered: the worst decile of BOOK days.
    threshold = float(np.quantile(book, 0.10))
    stress = book <= threshold
    periods = [f"{ts.year}" for ts in aligned.index]

    report = diversification_report(
        candidate.to_numpy(),
        sleeves,
        book,
        stress_mask=stress,
        period_labels=periods,
        candidate_weight=0.25,
        bootstrap_samples=2000,
    )

    net_sharpe = float(np.mean(candidate) / np.std(candidate, ddof=1) * np.sqrt(TRADING_DAYS))
    stressed = candidate.to_numpy()[stress]
    stressed_sharpe = float(np.mean(stressed) / np.std(stressed, ddof=1) * np.sqrt(TRADING_DAYS))
    # Newey-West is not recomputed here; the published figure for this identity is used, and the
    # point of the exercise is which gates bind, not to restate a statistic.
    published_newey_west_t = 1.267

    digest = "b" * 64
    evidence: dict[str, Any] = {
        "lineage": {
            "preregistration_sha256": digest,
            "data_manifest_sha256": digest,
            "diversification_report_sha256": digest,
            "code_commit": "abcdef1234567890",
            "family_trial_account": "cpi_surprise_size",
            "return_identity_id": "cpi_surprise_size_v1",
            "point_in_time_data": True,
            "survivorship_control": True,
            "corporate_action_control": True,
            "direction_locked": True,
            "parameters_locked": True,
        },
        # Granted in full: the question is which NUMERIC gates bind, not whether paperwork exists.
        "robustness": dict.fromkeys(contract["required_robustness"], True),
        "statistics": {
            "oos_observations": observations,
            "stressed_oos_observations": int(stress.sum()),
            "net_sharpe": net_sharpe,
            "stressed_sharpe": stressed_sharpe,
            "newey_west_t": published_newey_west_t,
            "deflated_sharpe": 0.0,
            "book_deflated_sharpe": 0.0,
            "pbo": {"status": "MEASURED", "value": 0.12, "family_variants": 6},
        },
        "diversification": {
            "absolute_beta": 0.04,
            "average_pairwise_correlation": report.average_pairwise_correlation,
            "average_pairwise_correlation_upper_95": report.average_pairwise_correlation_upper_95,
            "max_pairwise_correlation": report.max_pairwise_correlation,
            "max_stressed_pairwise_correlation": report.max_stressed_pairwise_correlation,
            "max_pairwise_correlation_upper_95": report.max_pairwise_correlation_upper_95,
            "max_stressed_pairwise_correlation_upper_95": (
                report.max_stressed_pairwise_correlation_upper_95
            ),
            "correlation_observations": observations,
        },
        "portfolio": {
            "book_sharpe_delta": report.book_sharpe_delta,
            "minimum_leave_one_period_out_book_sharpe_delta": (
                report.minimum_leave_one_period_out_book_sharpe_delta
            ),
            "book_max_drawdown_delta": report.book_max_drawdown_delta,
            "book_expected_shortfall_delta": report.book_expected_shortfall_delta,
            "book_sharpe_delta_lower_95": report.book_sharpe_delta,
            "book_expected_max_drawdown": 0.102,
        },
        "overlay": {
            "covariance_halflife_days": 21,
            "realized_vol_halflife_days": 240,
            "realized_vol_leg_is_unlevered": True,
        },
        "capacity": {},
        "execution": {},
    }

    verdict = evaluate_sleeve_evidence(evidence, contract)
    numeric_failures = [f for f in verdict.failures if f.startswith("threshold:")]
    missing = [f for f in verdict.failures if f.startswith("missing_")]

    result = {
        "schema": "canli.alphac-admission-dry-run.v1",
        "claim_boundary": (
            "Admissibility MECHANICS on already-registered identities. Registers no hypothesis "
            "identity, proposes no sleeve, and makes no claim about any candidate's edge. "
            "Capacity and execution evidence are left EMPTY on purpose so their failures are "
            "visible as evidence-gathering work rather than hidden behind a fabricated bundle."
        ),
        "candidate": CANDIDATE[0],
        "book_sleeves": sorted(sleeves),
        "curve_provenance": provenance,
        "window_is_bounded_by": min(
            provenance, key=lambda name: provenance[name]["last_observation"]
        )
        if provenance
        else None,
        "common_window_days": observations,
        "window_start": str(aligned.index[0].date()),
        "window_end": str(aligned.index[-1].date()),
        "measured": {
            "net_sharpe": net_sharpe,
            "stressed_sharpe": stressed_sharpe,
            "average_pairwise_correlation": report.average_pairwise_correlation,
            "average_pairwise_correlation_upper_95": report.average_pairwise_correlation_upper_95,
            "max_pairwise_correlation": report.max_pairwise_correlation,
            "book_sharpe_delta": report.book_sharpe_delta,
            "book_max_drawdown_delta": report.book_max_drawdown_delta,
            "book_expected_shortfall_delta": report.book_expected_shortfall_delta,
        },
        "decision": verdict.decision,
        "checks_evaluated": verdict.checks_evaluated,
        "numeric_gate_failures": numeric_failures,
        "missing_evidence_failures_count": len(missing),
        "honest_reading": (
            "The numeric failures are the interesting ones: they are what a real candidate cannot "
            "talk its way out of. Missing-evidence failures are work not yet done, not a verdict."
        ),
        "book_window_days_production_alignment": production_window,
        "commonly_active_days": observations,
        "book_common_window_days": observations,
        "why_two_counts": (
            "The production combiner aligns to a contiguous epoch-day index and treats an absent "
            f"day as flat, giving a window of {production_window} days. A correlation can only be "
            f"estimated from days on which both series are genuinely active, which is "
            f"{observations}. correlation_observations means the second. Reporting only the first "
            "would overstate how well the correlation is known; reporting only the second "
            "understates how long the book has run."
        ),
        "book_common_window_is_not_staleness": (
            "An earlier revision of this analysis called two of these curves stale. That was "
            "wrong and is corrected here. k30_dn_63 and crypto_carry_wk are BLESSED research "
            "artifacts, deliberately frozen -- k30_dn_63 is pinned by a signed construction-drift "
            "disclosure in scripts/alphamax_tick.sh, crypto_carry_wk is the canonical universe "
            "source several probes cite, and no tick regenerates either. Their 2026-06-01 end is "
            "by design. The common window is therefore a structural property of the evidence "
            "base, not neglect, and it cannot be extended by re-running anything."
        ),
        "the_observation_gate_is_bounded_by_the_BOOK": (
            "correlation_observations is capped by the common window of candidate AND book, so "
            "minimum_oos_observations constrains admission through the BOOK's history as well as "
            "the candidate's. On the window measured here that cap is "
            f"{observations} days, below the {contract['thresholds']['minimum_oos_observations']} "
            "the contract requires. This is a real property of the gate, not a defect in the "
            "candidate: a book whose own common history is short cannot admit anything, however "
            "long the candidate's record. Recorded rather than lowered -- a correlation is the "
            "quantity this whole programme turns on, and measuring it on one year is the reason "
            "the minimum was raised in the first place."
        ),
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    print(f"  candidate: {CANDIDATE[0]}  vs  {', '.join(sorted(sleeves))}")
    print(f"  common window: {observations} days "
          f"({result['window_start']} to {result['window_end']})")
    print(f"  net Sharpe {net_sharpe:+.4f} | rho_bar {report.average_pairwise_correlation:+.4f} "
          f"(upper95 {report.average_pairwise_correlation_upper_95:+.4f})")
    print(f"  book Sharpe delta {report.book_sharpe_delta:+.4f}")
    print(f"  decision: {verdict.decision}")
    print(f"  numeric gates failed ({len(numeric_failures)}):")
    for failure in numeric_failures:
        print(f"    - {failure}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
