"""Bind anomalous dividend rows to exact original-provider CSV records."""
import csv,io,json,zipfile,hashlib
from pathlib import Path
from decimal import Decimal
R=Path(__file__).resolve().parents[1];S=R/'evidence/alphamax-payment-source-full-20260913'
archive=Path('/Users/arhancanli/alphaforge/data/sharadar_raw/ACTIONS.zip');build=Path('/Users/arhancanli/alphaforge/artifacts/audit/sharadar_corporate_action_corrected_lake.json')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert 'sha256:'+sha(archive)==json.loads(build.read_text())['lineage']['raw_actions_archive_sha256']
keys={('TGT','2022-09-15'),('MCO','2022-10-26'),('HL','2023-06-14')};symbols={k[0] for k in keys};context=[];splits=[]
with zipfile.ZipFile(archive) as z:
 member,=[n for n in z.namelist() if n.endswith('.csv')]
 with z.open(member) as f:
  for line,row in enumerate(csv.DictReader(io.TextIOWrapper(f)),start=2):
   if row['ticker'] not in symbols:continue
   if row['action']=='split':splits.append(row)
   if '2022-01-01'<=row['date']<='2023-12-31':context.append({'csv_record_number_including_header':line,'row':row})
audit=json.loads((S/'match_audit.json').read_text())['matches'];result=[]
for symbol,date in sorted(keys):
 raw,=[x for x in context if x['row']['ticker']==symbol and x['row']['date']==date]
 original,=[x for x in audit if (x['symbol'],x['ex_date'])==(symbol,date)]
 assert raw['row']['action']=='dividend' and raw['row']['contraticker']=='N/A'
 factor=Decimal(1)
 for x in splits:
  if x['ticker']==symbol and x['date']>=date:factor*=Decimal(x['value'])
 assert factor==1 and Decimal(raw['row']['value'])==Decimal(str(original['cash_amount']))
 vendor_path=S/(symbol+'_dividends.bin');vendor=json.loads(vendor_path.read_bytes());assert not vendor.get('next_url')
 exact=[v for v in vendor['results'] if v['ex_dividend_date']==date];assert not exact
 result.append({'symbol':symbol,'date':date,'raw':raw,'frozen_event':original,'split_factor':str(factor),'exact_vendor_matches':exact,'conclusion':'Anomalous date and amount are original-provider dividend data, not generated by split transformation or duplicate ingestion. Economic validity remains separately adjudicated.'})
report={'status':'THREE_ANOMALOUS_EVENTS_BOUND_TO_ORIGINAL_PROVIDER','archive_member':member,'rows':result,'all_symbol_actions_2022_2023':context,'repair_requirements':{'TGT':'Issuer complete annual history and four already-matched ordinary distributions support candidate exclusion of extra September15. Preserve exact excluded row in separate partition; require both action and payment consumers to use same decision.','MCO':'Need complete annual issuer payout reconciliation or provider correction before classifying extra October26 as invalid; Q3 declaration alone only identifies collision.','HL':'Need complete2023 issuer payout reconciliation or provider correction; missing vendor match alone does not authorize deletion.'},'quarantine_contract':['Frozen baseline digest remains independently pinned.','Every original event belongs to exactly one reviewed/unresolved/excluded partition.','Exclusions require exact original-row binding, cited economic rationale and versioned review.','Reject any engine action/payment input that reintroduces an excluded event.','Propagate correction to feature inputs as well as cash accounting; retain old research and count new trials.','No returns until requested horizon is free of unresolved events and lifecycle constraints are satisfied.'],'no_events_excluded':True,'no_schedule_change':True,'no_returns':True,'sha256':{str(p):sha(p) for p in [Path(__file__),archive,build,S/'match_audit.json',S/'event_collision_audit_2022.json',*[S/(s+'_dividends.bin') for s in sorted(symbols)]]}}
with (S/'collision_origin_audit.json').open('x') as f:json.dump(report,f,indent=2)
for p,h in report['sha256'].items():assert sha(Path(p))==h
print(report['status']);print('Original-provider rows:',len(result),'context records:',len(context))
