"""Fingerprint every setting that decides how the LIVE book trades, derived from the code itself.

WHY THIS EXISTS. On 2026-08-21 a default in `BlendStrategy.__init__` was changed. No call site
passes that argument -- the crypto loop, the AlphaTrend gauntlet and the AlphaMax walk-forward all
take the default -- the walk-forwards are regenerated by the daily ticks, and `live_cycle.py`
submits the last leg's weights straight to the broker. So the change would have re-sized two
broker-executed sleeves on the next tick. Nothing caught it. There is an 85-check ceremony around
ADMITTING a sleeve and none at all around changing how the live book sizes itself, which is
backwards: the live change touches the forward record, and the forward record is the only evidence
that will ever defeat deflation.

A DEFAULT NOBODY OVERRIDES IS NOT A DEFAULT, IT IS THE PRODUCTION SETTING. This fingerprints that
surface so a change to it must be declared, the way a schema migration must be declared.

Derived, never transcribed: the strategy settings come from `inspect.signature`, and the book
composition from the published state. A hand-maintained list of "things that matter" goes stale
exactly when it matters most.

Reads no market data and runs nothing: this is a description of configuration.
"""

from __future__ import annotations

import hashlib
import inspect
import json
from pathlib import Path
from typing import Any

from alphaforge.portfolio.strategy import BlendStrategy

REPO = Path(__file__).resolve().parents[1]
STATE = REPO / "data" / "paper" / "state.json"
OUTPUT = REPO / "artifacts" / "engineering" / "live_config_fingerprint.json"

# Constructor parameters that do NOT decide how the book trades: they are wiring, supplied at every
# call site, or non-numeric plumbing. Everything else is fingerprinted. Listing the exclusions
# rather than the inclusions is deliberate -- a new sizing parameter is then covered by default,
# and forgetting to add it cannot silently drop it from the fingerprint.
_NOT_SIZING = frozenset({"self", "settings", "signal_frame", "mu_provider"})


def strategy_settings() -> dict[str, Any]:
    """Every BlendStrategy default that reaches production because nothing overrides it."""
    signature = inspect.signature(BlendStrategy.__init__)
    return {
        name: parameter.default
        for name, parameter in signature.parameters.items()
        if name not in _NOT_SIZING and parameter.default is not inspect.Parameter.empty
    }


def book_composition() -> dict[str, Any]:
    """The book's SPECIFICATION only: which sleeves, at what weights, and the disclosed tilt.

    Deliberately excludes equity, marks, dates and anything else that moves because the book is
    running. A fingerprint that changed every day would be ignored within a week.
    """
    if not STATE.exists():
        return {}
    book = json.loads(STATE.read_text()).get("book", {})
    tilt = book.get("strategic_tilt", {}) or {}
    return {
        "sleeves": {
            str(sleeve.get("key")): sleeve.get("weight") for sleeve in book.get("sleeves", [])
        },
        "strategic_tilt_pct": tilt.get("pct"),
        "strategic_tilt_mix": tilt.get("mix"),
    }


def build_fingerprint() -> dict[str, Any]:
    surface = {
        "strategy_settings": strategy_settings(),
        "book_composition": book_composition(),
    }
    canonical = json.dumps(surface, sort_keys=True, separators=(",", ":")).encode()
    return {
        "schema": "canli.alphac-live-config-fingerprint.v1",
        "what_this_covers": (
            "Every setting that decides how the live book trades: the BlendStrategy defaults that "
            "reach production because no call site overrides them, and the book's sleeve "
            "composition, weights and disclosed tilt. Derived from inspect.signature and the "
            "published state, never from a hand-maintained list."
        ),
        "what_this_deliberately_excludes": (
            "Anything that moves because the book is running -- equity, marks, dates, live days. "
            "A fingerprint that changed daily would be ignored within a week."
        ),
        "surface": surface,
        "fingerprint": f"sha256:{hashlib.sha256(canonical).hexdigest()}",
    }


def main() -> int:
    fingerprint = build_fingerprint()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(fingerprint, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    print(f"  {fingerprint['fingerprint']}")
    for name, value in sorted(fingerprint["surface"]["strategy_settings"].items()):
        print(f"    {name:30} = {value!r}")
    composition = fingerprint["surface"]["book_composition"]
    print(f"    sleeves: {composition.get('sleeves')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
