"""A change to how the live book trades must be declared before it ships.

THE ASYMMETRY THIS CLOSES. Admitting a sleeve runs 85 evidence checks. Changing how the entire
book sizes itself ran none — and on 2026-08-21 a constructor default was changed that would have
re-sized two broker-executed sleeves on the next daily tick, because no call site passes that
argument, the walk-forwards are regenerated by the ticks, and live_cycle.py submits the last leg's
weights straight to the broker. The commit said "nothing was re-run". It was reverted the same day
after an adversarial audit found it, not after a test did.

WHY IT MATTERS MORE THAN IT LOOKS. The forward record is the only evidence that can defeat
deflation — a pre-registered book run forward is N=1, hurdle 0.88 at five years against 2.44 for a
backtest selected from 162 identities. That record is fourteen days old. A silent live change does
not just alter the book, it contaminates the one asset that cannot be bought later.

This is a declare-to-change gate, not a freeze: changing the live book is allowed, changing it
WITHOUT SAYING SO is not.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO = Path(__file__).parents[2]
CONTRACT = REPO / "config" / "live_change_contract.json"

_spec = importlib.util.spec_from_file_location(
    "export_live_config_fingerprint", REPO / "scripts" / "export_live_config_fingerprint.py"
)
assert _spec is not None and _spec.loader is not None
fingerprinter = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fingerprinter)


def _contract() -> dict:
    assert CONTRACT.exists(), f"no live-change contract at {CONTRACT}"
    return json.loads(CONTRACT.read_text())


def test_the_live_configuration_matches_what_is_declared() -> None:
    """The whole gate. If this fails, something about how the live book trades has moved."""
    declared = _contract()
    measured = fingerprinter.build_fingerprint()

    assert measured["fingerprint"] == declared["declared_fingerprint"], (
        "the live trading configuration has changed without being declared.\n"
        f"  declared: {declared['declared_fingerprint']}\n"
        f"  measured: {measured['fingerprint']}\n"
        "A default nobody overrides is not a default, it is the production setting, and the "
        "walk-forwards that feed the broker are regenerated by the daily ticks. Measure the "
        "change on the LIVE path, add it to change_log in config/live_change_contract.json with "
        "its reason and evidence, re-run scripts/export_live_config_fingerprint.py, and expect "
        "the forward record to be marked at that date."
    )


def test_the_declared_surface_is_the_measured_surface() -> None:
    """Not just the hash: the readable surface must match too, so a diff shows WHAT moved."""
    declared = _contract()["declared_surface"]
    measured = fingerprinter.build_fingerprint()["surface"]
    assert declared == measured


def test_every_sizing_parameter_is_covered() -> None:
    """The fingerprint lists EXCLUSIONS, so a new sizing parameter is covered by default.

    Pinned as an invariant over the constructor rather than against today's parameter names: a
    parameter added tomorrow is inside the fingerprint unless someone deliberately excludes it,
    which is the safe direction for a guard on the live book.
    """
    import inspect

    from alphaforge.portfolio.strategy import BlendStrategy

    covered = set(fingerprinter.strategy_settings())
    defaults = {
        name
        for name, parameter in inspect.signature(BlendStrategy.__init__).parameters.items()
        if parameter.default is not inspect.Parameter.empty
    }
    uncovered = sorted(defaults - covered - set(fingerprinter._NOT_SIZING))
    assert not uncovered, (
        f"these BlendStrategy defaults reach production but are outside the fingerprint: "
        f"{uncovered}"
    )


def test_the_change_log_is_not_empty_and_carries_reasons() -> None:
    """A log of changes with no reasons is a changelog, not a control."""
    contract = _contract()
    log = contract["change_log"]
    assert log, "the change log must record at least the initial declaration"
    for entry in log:
        for field in ("date", "change", "reason", "contaminates_forward_record"):
            assert field in entry, f"change_log entry missing {field!r}: {entry}"
        assert len(entry["reason"]) > 40, (
            "a one-word reason is not a reason; this entry would not tell a future reader why the "
            "live book changed"
        )


def test_the_guard_can_fail(monkeypatch: pytest.MonkeyPatch) -> None:
    """A check that cannot fail is worse than no check, so prove this one bites."""
    real = fingerprinter.strategy_settings

    def mutated() -> dict:
        settings = dict(real())
        settings["cov_window_bars"] = 21  # the kind of change that re-sizes the live book
        return settings

    monkeypatch.setattr(fingerprinter, "strategy_settings", mutated)
    measured = fingerprinter.build_fingerprint()
    assert measured["fingerprint"] != _contract()["declared_fingerprint"]
