"""A publish step that READS another step's output must be invoked after it.

WHAT WENT WRONG. `scripts/paper_trading_state.py` writes `data/paper/state.json`.
`scripts/glassbox_export.py` reads it. Both publish jobs called glassbox FIRST, so every
glass-box artifact built from that state was rendered from the PREVIOUS cycle -- including
`track_record.json`, the artifact behind the site's headline "Proven in the Open" record.

That is not a cosmetic lag. When the AlphaVintage correction landed, `paper-state.json` carried
the withdrawn figure's retraction and `track_record.json`, generated in the same run seconds
earlier, went on asserting net Sharpe 0.3403 bare -- twice, on the live site. The pipeline was
publishing the correction and the error in one run for the second time in this project's life.

WHY A TEST AND NOT A COMMENT. Every edge here is file-mediated: nothing in either shell script
says glassbox needs state.json, so the ordering looks arbitrary and stayed wrong through every
edit to these files. This test makes the invisible edges explicit and checks each declared edge
against the scripts themselves, so a wrong declaration fails rather than quietly enforcing
nothing. It caught one on its first run.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]

#: (producer, shared artifact, consumers that must run after it, [pipelines this edge applies to]).
#: A list, not a dict keyed by producer: paper_trading_state.py hands two DIFFERENT artifacts to
#: two different sets of consumers, and a producer-keyed mapping silently loses the second edge.
#:
#: The optional 4th element scopes an edge to a subset of PIPELINES; omitting it (a 3-tuple, every
#: edge above this comment) means "both". This exists for the sleeve-publication chain below: those
#: producers run ONLY in live_publish.sh (they are near-static evidence audits, not hourly-moving
#: state), so declaring them as bare 3-tuples would make
#: test_the_pipeline_exists_and_invokes_every_producer fail for live_tick.sh -- not because the
#: ordering is wrong, but because the check would be asking a pipeline to invoke a script that was
#: never meant to run there. A gate that cannot be satisfied by a correct pipeline is not a
#: stricter gate, it is a broken one; scoping the edge is what keeps it checking something real.
EDGES: tuple[
    tuple[str, str, tuple[str, ...]] | tuple[str, str, tuple[str, ...], tuple[str, ...]], ...
] = (
    (
        "export_alpaca_broker_reconciliation.py",
        "var/trading_equity.sqlite",
        ("paper_trading_state.py", "audit_record_continuity.py"),
    ),
    (
        "paper_trading_state.py",
        "data/paper/state.json",
        ("glassbox_export.py", "transparency_log.py", "research_export.py"),
    ),
    # The same producer also copies the state out to the site workspaces; the lineage audit reads
    # THAT copy, not data/paper/state.json. Declaring it against the wrong artifact is precisely
    # the mistake test_every_declared_edge_is_real caught the first time it ran.
    (
        "paper_trading_state.py",
        "meridian/public/paper-state.json",
        ("audit_sleeve_family_lineage.py",),
    ),
    # The lineage audit reads the PUBLISHED kill ledger too, not just the published book. Both of
    # its inputs are written by earlier steps, and both edges have to be declared: an undeclared
    # edge is not a weaker guard, it is no guard, and a later reorder would break it in silence.
    # research_export.py joined this edge when the kill papers were added: it renders one paper
    # per killed candidate from the PUBLISHED kill log, so it must run after the step that writes
    # it. Declaring the new consumer rather than relying on the existing edge -- an undeclared
    # edge is not a weaker guard, it is no guard, and a later reorder would break it in silence.
    (
        "glassbox_export.py",
        "meridian/public/glassbox/kill_log.json",
        (
            "audit_sleeve_family_lineage.py",
            "build_trial_packet_manifest.py",
            "research_export.py",
        ),
    ),
    # The continuity report is REGENERATED by the tick before it is published. An artifact
    # nothing regenerates is a screenshot, not a check — and a stale continuity report is worse
    # than none, because it asserts the forward record is whole.
    (
        "audit_record_continuity.py",
        "artifacts/engineering/record_continuity.json",
        ("research_export.py",),
    ),
    (
        "audit_sleeve_family_lineage.py",
        "artifacts/discovery/sleeve_family_lineage_audit.json",
        ("research_export.py",),
    ),
    # research_export.py copies the lint-debt contract into both site bundles verbatim, so the
    # exporter that derives it from the current source has to run first. Until 2026-08-20 it ran
    # in neither pipeline — only in CI, where the output is discarded — so the published
    # engineering-quality claim was pinned to whenever a human last ran it by hand.
    (
        "export_lint_debt_contract.py",
        "artifacts/engineering/lint_debt_contract.json",
        ("research_export.py",),
    ),
    (
        "build_trial_packet_manifest.py",
        "artifacts/research/trial_packet_manifest.json",
        ("seal_legacy_research_epoch.py", "research_export.py"),
    ),
    (
        "build_identity_trial_packets.py",
        "artifacts/research/trial_packets",
        ("build_trial_packet_manifest.py",),
    ),
    (
        "transparency_log.py",
        "meridian/public/glassbox/transparency_log.json",
        ("evaluate_forward_evidence_maturity.py",),
    ),
    (
        "export_crypto_position_attribution.py",
        "artifacts/engineering/crypto_position_attribution.json",
        ("evaluate_forward_evidence_maturity.py", "research_export.py"),
    ),
    (
        "verify_crypto_position_attribution_rollout.py",
        "artifacts/engineering/crypto_position_attribution_rollout_verification.json",
        ("evaluate_forward_evidence_maturity.py", "research_export.py"),
    ),
    (
        "analyze_current_book_drawdown.py",
        "artifacts/analysis/current_book_drawdown/result.json",
        (
            "analyze_current_book_diversification.py",
            "seal_forward_drawdown_evidence.py",
            "evaluate_forward_evidence_maturity.py",
            "research_export.py",
        ),
    ),
    (
        "analyze_current_book_diversification.py",
        "artifacts/analysis/current_book_diversification/result.json",
        ("evaluate_forward_evidence_maturity.py", "research_export.py"),
    ),
    (
        "seal_forward_drawdown_evidence.py",
        "artifacts/engineering/forward_drawdown_evidence.json",
        ("evaluate_forward_evidence_maturity.py", "research_export.py"),
    ),
    (
        "evaluate_forward_evidence_maturity.py",
        "artifacts/engineering/forward_evidence_maturity.json",
        ("sync_readme_forward_evidence.py", "research_export.py"),
    ),
    (
        "seal_legacy_research_epoch.py",
        "artifacts/research/legacy_research_epoch_closure.json",
        ("research_export.py",),
    ),
    (
        "seal_next_sleeve_selection.py",
        "artifacts/analysis/next_sleeve_selection.json",
        ("research_export.py",),
    ),
    # SLEEVE-PUBLICATION EVIDENCE CHAIN (added 2026-09-06). Each of these reads the previous
    # one's output, and every one of them drifted silently for the same reason: nothing in
    # either publish job ever ran them, so "persisted receipt matches current sources" tests
    # went red the moment a tracked publication bundle was rebound underneath them. Publish-only
    # (see the EDGES docstring above) because they audit near-static publication evidence, not
    # state that moves hourly.
    (
        "package_all_sleeve_review_archives.py",
        "artifacts/publication/all_sleeve_review_archives.json",
        (
            "audit_clean_workspace_reproduction_contracts.py",
            "build_repository_submission_worksheets.py",
            "build_stanford_evidence_map.py",
        ),
        ("scripts/live_publish.sh",),
    ),
    (
        "audit_all_sleeve_data_rights.py",
        "artifacts/publication/all_sleeve_data_rights_audit.json",
        ("audit_clean_workspace_reproduction_contracts.py", "audit_external_publication_readiness.py"),
        ("scripts/live_publish.sh",),
    ),
    (
        "audit_clean_workspace_reproduction_contracts.py",
        "artifacts/publication/clean_workspace_reproduction_audit.json",
        ("build_repository_submission_worksheets.py", "build_stanford_evidence_map.py"),
        ("scripts/live_publish.sh",),
    ),
    (
        "audit_wave1_data_rights.py",
        "artifacts/publication/wave1_data_rights_audit.json",
        ("package_wave1_release_candidates.py",),
        ("scripts/live_publish.sh",),
    ),
    (
        "build_repository_submission_worksheets.py",
        "artifacts/publication/repository_submission_worksheets.json",
        ("build_stanford_evidence_map.py",),
        ("scripts/live_publish.sh",),
    ),
    # build_stanford_evidence_map.py runs in BOTH pipelines (its live counters -- broker,
    # forward-evidence, mutation coverage -- move hourly), so this edge is a plain 3-tuple like
    # the ones above it, not scoped like its Group-A inputs.
    (
        "build_stanford_evidence_map.py",
        "artifacts/portfolio/stanford_cs_evidence_map.json",
        ("research_export.py",),
    ),
)

PIPELINES = ("scripts/live_tick.sh", "scripts/live_publish.sh")


def _invocation_lines(script: Path, name: str) -> list[int]:
    """Line numbers where `script` actually invokes `name` (not lines that merely mention it)."""
    pattern = re.compile(rf"^\s*[^#\n]*\bpython\s+scripts/{re.escape(name)}\b")
    return [n for n, line in enumerate(script.read_text().splitlines(), 1) if pattern.match(line)]


def _edge_pipelines(edge: tuple) -> tuple[str, ...]:
    """Which PIPELINES an EDGES entry applies to: its 4th element, or both if omitted."""
    return edge[3] if len(edge) > 3 else PIPELINES


def _references(source: str, artifact: str) -> bool:
    """Does `source` name `artifact`, as a literal path or as assembled path segments?

    Exporters write either form -- `Path("data/paper/state.json")` or
    `ROOT.parent / "meridian" / "public" / "paper-state.json"` -- so checking only the literal
    would silently accept a stale declaration for any script that uses the second.
    """
    if artifact in source:
        return True
    return all(f'"{segment}"' in source for segment in artifact.split("/"))


@pytest.mark.parametrize("pipeline", PIPELINES)
def test_the_pipeline_exists_and_invokes_every_producer(pipeline: str) -> None:
    """Guards the guard: if the scan finds no invocation, every ordering case below is vacuous."""
    script = REPO / pipeline
    assert script.exists(), f"{pipeline} missing — this test cannot report a pass"
    for edge in EDGES:
        if pipeline not in _edge_pipelines(edge):
            continue
        producer = edge[0]
        assert _invocation_lines(script, producer), (
            f"{pipeline} never invokes {producer}; either the pipeline changed shape or the "
            f"invocation regex no longer matches it. Both make the ordering assertion vacuous."
        )


@pytest.mark.parametrize("pipeline", PIPELINES)
def test_consumers_run_after_the_step_that_writes_their_input(pipeline: str) -> None:
    script = REPO / pipeline
    for edge in EDGES:
        if pipeline not in _edge_pipelines(edge):
            continue
        producer, artifact, consumers = edge[0], edge[1], edge[2]
        produced_at = _invocation_lines(script, producer)
        assert len(produced_at) == 1, (
            f"{pipeline} invokes {producer} {len(produced_at)} times at lines {produced_at}; "
            f"with more than one write the ordering below is ambiguous, so fix the pipeline "
            f"rather than this test."
        )
        for consumer in consumers:
            for consumed_at in _invocation_lines(script, consumer):
                assert consumed_at > produced_at[0], (
                    f"{pipeline}:{consumed_at} runs {consumer} BEFORE {producer} "
                    f"(line {produced_at[0]}). {consumer} reads {artifact}, which {producer} "
                    f"writes, so it would publish the previous cycle's state."
                )


def test_every_declared_edge_is_real() -> None:
    """The list above is a claim about the code; check it against the code.

    Without this, a stale entry would keep enforcing an order for a dependency that no longer
    exists, and a mis-declared one would enforce nothing at all while looking like coverage.
    """
    for edge in EDGES:
        producer, artifact, consumers = edge[0], edge[1], edge[2]
        producer_src = (REPO / "scripts" / producer).read_text()
        assert _references(producer_src, artifact), (
            f"{producer} does not reference {artifact}, which it is declared to write"
        )
        for consumer in consumers:
            consumer_src = (REPO / "scripts" / consumer).read_text()
            assert _references(consumer_src, artifact), (
                f"{consumer} is declared a consumer of {artifact} but never references it; "
                f"remove it from EDGES or fix the path."
            )


def test_the_reference_check_can_fail() -> None:
    """A path nothing mentions must not read as referenced."""
    assert not _references("nothing to see here", "data/paper/state.json")
    assert not _references('open("data/paper/other.json")', "data/paper/state.json")
    assert _references('open("data/paper/state.json")', "data/paper/state.json")
    assert _references('ROOT / "data" / "paper" / "state.json"', "data/paper/state.json")
