"""A change to how the live book trades must be declared before it ships.

THE ASYMMETRY THIS CLOSES. Admitting a sleeve runs 85 evidence checks. Changing how the entire
book sizes itself ran none — and on 2026-08-21 a constructor default was changed that would have
re-sized two broker-executed sleeves on the next daily tick, because no call site passes that
argument, the walk-forwards are regenerated by the ticks, and live_cycle.py submits the last leg's
weights straight to the broker. The commit said "nothing was re-run". It was reverted the same day
after an adversarial audit found it, not after a test did.

WHY IT MATTERS MORE THAN IT LOOKS. The forward record is the only evidence that can defeat
deflation — a pre-registered book run forward is N=1, hurdle 0.88 at five years against 2.44 for a
backtest selected from 162 identities. That record is fourteen days old. A silent live change does
not just alter the book, it contaminates the one asset that cannot be bought later.

This is a declare-to-change gate, not a freeze: changing the live book is allowed, changing it
WITHOUT SAYING SO is not.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO = Path(__file__).parents[2]
CONTRACT = REPO / "config" / "live_change_contract.json"

_spec = importlib.util.spec_from_file_location(
    "export_live_config_fingerprint", REPO / "scripts" / "export_live_config_fingerprint.py"
)
assert _spec is not None and _spec.loader is not None
fingerprinter = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fingerprinter)


def _contract() -> dict:
    assert CONTRACT.exists(), f"no live-change contract at {CONTRACT}"
    return json.loads(CONTRACT.read_text())


def test_the_live_configuration_matches_what_is_declared() -> None:
    """The whole gate. If this fails, something about how the live book trades has moved."""
    declared = _contract()
    measured = fingerprinter.build_fingerprint()

    assert measured["fingerprint"] == declared["declared_fingerprint"], (
        "the live trading configuration has changed without being declared.\n"
        f"  declared: {declared['declared_fingerprint']}\n"
        f"  measured: {measured['fingerprint']}\n"
        "A default nobody overrides is not a default, it is the production setting, and the "
        "walk-forwards that feed the broker are regenerated by the daily ticks. Measure the "
        "change on the LIVE path, add it to change_log in config/live_change_contract.json with "
        "its reason and evidence, re-run scripts/export_live_config_fingerprint.py, and expect "
        "the forward record to be marked at that date."
    )


def test_the_declared_surface_is_the_measured_surface() -> None:
    """Not just the hash: the readable surface must match too, so a diff shows WHAT moved."""
    declared = _contract()["declared_surface"]
    measured = fingerprinter.build_fingerprint()["surface"]
    assert declared == measured


def test_every_sizing_parameter_is_covered() -> None:
    """The fingerprint lists EXCLUSIONS, so a new sizing parameter is covered by default.

    Pinned as an invariant over the constructor rather than against today's parameter names: a
    parameter added tomorrow is inside the fingerprint unless someone deliberately excludes it,
    which is the safe direction for a guard on the live book.
    """
    import inspect

    from alphaforge.portfolio.strategy import BlendStrategy

    covered = set(fingerprinter.strategy_settings())
    defaults = {
        name
        for name, parameter in inspect.signature(BlendStrategy.__init__).parameters.items()
        if parameter.default is not inspect.Parameter.empty
    }
    uncovered = sorted(defaults - covered - set(fingerprinter._NOT_SIZING))
    assert not uncovered, (
        f"these BlendStrategy defaults reach production but are outside the fingerprint: "
        f"{uncovered}"
    )


def test_the_change_log_is_not_empty_and_carries_reasons() -> None:
    """A log of changes with no reasons is a changelog, not a control."""
    contract = _contract()
    log = contract["change_log"]
    assert log, "the change log must record at least the initial declaration"
    for entry in log:
        for field in ("date", "change", "reason", "contaminates_forward_record"):
            assert field in entry, f"change_log entry missing {field!r}: {entry}"
        assert len(entry["reason"]) > 40, (
            "a one-word reason is not a reason; this entry would not tell a future reader why the "
            "live book changed"
        )


def test_the_guard_can_fail(monkeypatch: pytest.MonkeyPatch) -> None:
    """A check that cannot fail is worse than no check, so prove this one bites."""
    real = fingerprinter.strategy_settings

    def mutated() -> dict:
        settings = dict(real())
        settings["cov_window_bars"] = 21  # the kind of change that re-sizes the live book
        return settings

    monkeypatch.setattr(fingerprinter, "strategy_settings", mutated)
    measured = fingerprinter.build_fingerprint()
    assert measured["fingerprint"] != _contract()["declared_fingerprint"]


def test_every_field_in_the_surface_actually_moves_the_fingerprint() -> None:
    """A field recorded in the surface but not reaching the hash is decoration, not coverage.

    Stated over the WHOLE surface rather than against a list of field names, so a setting added
    tomorrow is checked the day it appears. This is the invariant that would have caught the
    original gap: the overlay's vol target, the ladder's halve and flatten depths, the halt
    cooldown, the staleness limit and the inviolable per-name cap are read off Settings rather
    than passed to the constructor, so all eight sat outside a fingerprint that claimed to cover
    "how the live book trades".
    """
    baseline = fingerprinter.build_fingerprint()
    surface = baseline["surface"]
    assert surface, "an empty surface would make this guard vacuous"

    def bump(value: object) -> object:
        """Every branch must actually CHANGE the value.

        A branch that returns its input unchanged reports the field as uncovered when it is not.
        That happened on this test's first run: `sleeves` and `strategic_tilt_mix` are dicts, the
        helper returned them as-is, and the guard accused a fingerprint that hashes them
        correctly. The check would have been measuring the helper, not the thing it guards.
        """
        if isinstance(value, bool):
            return not value
        if isinstance(value, (int, float)):
            return value + 1
        if isinstance(value, str):
            return f"{value}_mutated"
        if isinstance(value, dict):
            return {**value, "__mutated__": 1}
        if isinstance(value, list):
            return [*value, "__mutated__"]
        return "__mutated__" if value is None else value

    unmoved: list[str] = []
    for section, values in surface.items():
        if not isinstance(values, dict):
            continue
        for field, value in values.items():
            mutated = json.loads(json.dumps(surface))
            mutated[section][field] = bump(value)
            if fingerprinter.canonical_fingerprint(mutated) == baseline["fingerprint"]:
                unmoved.append(f"{section}.{field}")

    assert not unmoved, (
        f"these fields are recorded in the live-config surface but do not reach the fingerprint, "
        f"so changing them would not be detected: {unmoved}"
    )


def test_the_risk_path_is_inside_the_surface() -> None:
    """Named explicitly because these were the fields that were missing, and why they were.

    They are not constructor defaults: BlendStrategy reads them off Settings, so a guard built by
    inspecting the constructor signature cannot see them however carefully it is written.
    """
    surface = fingerprinter.build_fingerprint()["surface"]
    assert "risk_path_settings" in surface
    for field in (
        "vol_target_ann",
        "vol_scale_max",
        "gross_max",
        "dd_halve_gross",
        "dd_flat_halt",
        "flat_cooldown_bars",
        "staleness_max_bars",
        "w_max",
    ):
        assert field in surface["risk_path_settings"], f"{field} is outside the live-config guard"


# --------------------------------------------------------------------------------------------
# The PUBLISHED record must carry the configuration that produced it (backlog A3)
# --------------------------------------------------------------------------------------------

PUBLISHED_STATES = (
    REPO.parent / "meridian" / "public" / "paper-state.json",
    REPO.parent / "meridian-app" / "public" / "paper-state.json",
    REPO / "data" / "paper" / "state.json",
)


def _published_states() -> list[tuple[Path, dict]]:
    found = [(p, json.loads(p.read_text())) for p in PUBLISHED_STATES if p.exists()]
    assert found, (
        "no published paper-state.json found on any host or in the repo; this guard would pass "
        "vacuously, which is the failure mode it exists to prevent"
    )
    return found


def test_the_published_record_says_which_configuration_produced_it() -> None:
    """A curve that cannot say what it was cannot be read as one experiment.

    The forward record is the only evidence that can defeat deflation, and its value is entirely
    in being ONE continuous test of ONE specification. Without a stamp, a reader cannot tell a
    continuous record from a curve that changed underneath itself.
    """
    for path, state in _published_states():
        assert "live_config" in state, f"{path} publishes a record with no configuration stamp"
        stamp = state["live_config"]
        for field in ("fingerprint", "declared_fingerprint", "matches_declaration"):
            assert field in stamp, f"{path} stamp is missing {field!r}"
        assert stamp["fingerprint"].startswith("sha256:")


def test_the_published_stamp_agrees_with_the_declaration() -> None:
    """Published, measured and declared must be the same value — all three, not two of three."""
    declared = _contract()["declared_fingerprint"]
    measured = fingerprinter.build_fingerprint()["fingerprint"]
    for path, state in _published_states():
        stamp = state["live_config"]
        assert stamp["declared_fingerprint"] == declared, (
            f"{path} carries a stale declaration: {stamp['declared_fingerprint']} vs {declared}"
        )
        assert stamp["fingerprint"] == measured, (
            f"{path} was stamped under a different configuration than the one running now: "
            f"{stamp['fingerprint']} vs {measured}. Either the record is stale or the live "
            "configuration moved after it was written."
        )
        assert stamp["matches_declaration"] is True, (
            f"{path} records a configuration that does not match the declaration. The record now "
            "contains a discontinuity; declare it in config/live_change_contract.json and mark "
            "the forward record at this date."
        )


def test_the_stamp_is_a_boolean_not_a_refusal() -> None:
    """`matches_declaration` must be REPORTED, never used to refuse to write the record.

    Refusing to publish because a configuration changed would destroy the record in order to
    protect it. A marked discontinuity is recoverable; a hole in the forward record is not, and a
    hole is the same harm the whole live-change ceremony exists to prevent.
    """
    source = (REPO / "scripts" / "paper_trading_state.py").read_text()
    assert "matches_declaration" in source
    for line in source.splitlines():
        stripped = line.strip()
        if "matches_declaration" not in stripped or stripped.startswith("#"):
            continue
        assert not stripped.startswith(("raise", "assert", "sys.exit")), (
            "the provenance stamp must not be able to abort the record it stamps: "
            f"{stripped!r}"
        )
