"""Execution layer (execDesign.md §8): the Broker interface and its brokers.

PAPER ONLY in v1. The live loop holds a :class:`Broker` and is agnostic to
whether fills are simulated or real::

    Broker (ABC, sync)
      |- PaperBroker  -- simulated fills by WALKING a real order-book snapshot
      |                  (leakageCritique.md finding 8: never priced by the cost
      |                  model; the model is a slippage CROSS-CHECK only)
      `- CCXTBroker   -- real money, a NotArmed STUB; every order-mutating call
                         raises NotArmedError (arming is a deliberate Phase-8+
                         step, never reachable by accident)

Order books are supplied to :class:`PaperBroker` through an
:class:`OrderBookSource` -- :class:`CCXTOrderBookSource` live,
:class:`FakeOrderBookSource` for offline deterministic tests. The paper account
serializes to a plain :class:`PaperState` so a crashed live process resumes the
identical book.

All timestamps are :data:`~alphaforge.core.time.Ms` (epoch ms, UTC); all money
is float64 quote units. Nothing here imports network at module load.
"""

from alphaforge.execution.borrow import (
    BorrowDataProvider,
    BorrowQuote,
    BorrowStatus,
    LocateDecision,
    LocateStatus,
    RecallInstruction,
    RecallNotice,
    StaticBorrowDataProvider,
    accrue_borrow_charge,
    evaluate_locate,
    incremental_short_qty,
    recall_instruction,
)
from alphaforge.execution.broker import Broker, BrokerAck, OpenOrder, OrderBook
from alphaforge.execution.ccxt_broker import ARM_ENV_VAR, CCXTBroker
from alphaforge.execution.corporate_actions import CorporateAction, CorporateActionType
from alphaforge.execution.financing import (
    DayCountBasis,
    FinancingAccrual,
    FinancingDataProvider,
    FinancingQuote,
    StaticFinancingDataProvider,
    accrue_financing,
)
from alphaforge.execution.futures import (
    ContractLiquidity,
    FuturesChain,
    FuturesContract,
    FuturesExecutionBlocked,
    FuturesPriceLimit,
    RollAction,
    RollDecision,
    RollPolicy,
    RollSnapshot,
    select_roll,
    variation_margin,
)
from alphaforge.execution.market_status import (
    MarketStatus,
    MarketStatusEvent,
    MarketStatusProvider,
    StaticMarketStatusProvider,
    execution_block_reason,
)
from alphaforge.execution.options import (
    AssignmentNotice,
    ExerciseStyle,
    OptionContract,
    OptionDelivery,
    OptionQuote,
    OptionRight,
    OptionSettlement,
    OptionSurfaceIntegrityError,
    OptionSurfaceSnapshot,
    OptionSurfaceViolation,
    OptionSurfaceViolationType,
    SettlementStyle,
    apply_assignment,
    expiry_delivery,
    intrinsic_value,
)
from alphaforge.execution.options_deliverables import (
    OptionAssetDelta,
    OptionBasketDelivery,
    OptionCashAmount,
    OptionCashDelta,
    OptionDeliverableAsset,
    OptionDeliverableDataProvider,
    OptionDeliverableTerms,
    StaticOptionDeliverableDataProvider,
    apply_adjusted_assignment,
    apply_physical_deliverable,
    expiry_adjusted_delivery,
)
from alphaforge.execution.options_fees import (
    OptionFeeAssessment,
    OptionFeeComponent,
    OptionFeeDataProvider,
    OptionFeeEvent,
    OptionFeeLine,
    OptionFeeLiquidity,
    OptionFeeRounding,
    OptionFeeSchedule,
    OptionFeeSide,
    StaticOptionFeeDataProvider,
    assess_option_lifecycle_fees,
    assess_option_trade_fees,
)
from alphaforge.execution.options_margin import (
    OptionMarginAssessment,
    OptionMarginDataProvider,
    OptionMarginPolicy,
    OptionMarginPosition,
    OptionMarginRequirementType,
    OptionMarginScenario,
    OptionMarginScenarioLoss,
    OptionMarginScenarioPrice,
    OptionMarginSnapshot,
    StaticOptionMarginDataProvider,
    assess_option_scenario_margin,
)
from alphaforge.execution.options_packages import (
    DISPLAYED_ATOMIC_CROSS_ASSUMPTION,
    OptionLegExecution,
    OptionPackageExecution,
    OptionPackageExecutionStatus,
    OptionPackageLeg,
    OptionPackageMarketStatus,
    OptionPackageOrder,
    OptionPackageRejectReason,
    OptionPackageTimeInForce,
    execute_displayed_option_package,
)
from alphaforge.execution.paper import (
    CCXTOrderBookSource,
    FakeOrderBookSource,
    OrderBookSource,
    PaperBroker,
    PaperFillAudit,
    PaperPosition,
    PaperState,
    WalkedFill,
    walk_book,
)

__all__ = [
    "ARM_ENV_VAR",
    "DISPLAYED_ATOMIC_CROSS_ASSUMPTION",
    "AssignmentNotice",
    "BorrowDataProvider",
    "BorrowQuote",
    "BorrowStatus",
    "Broker",
    "BrokerAck",
    "CCXTBroker",
    "CCXTOrderBookSource",
    "ContractLiquidity",
    "CorporateAction",
    "CorporateActionType",
    "DayCountBasis",
    "ExerciseStyle",
    "FakeOrderBookSource",
    "FinancingAccrual",
    "FinancingDataProvider",
    "FinancingQuote",
    "FuturesChain",
    "FuturesContract",
    "FuturesExecutionBlocked",
    "FuturesPriceLimit",
    "LocateDecision",
    "LocateStatus",
    "MarketStatus",
    "MarketStatusEvent",
    "MarketStatusProvider",
    "OpenOrder",
    "OptionAssetDelta",
    "OptionBasketDelivery",
    "OptionCashAmount",
    "OptionCashDelta",
    "OptionContract",
    "OptionDeliverableAsset",
    "OptionDeliverableDataProvider",
    "OptionDeliverableTerms",
    "OptionDelivery",
    "OptionFeeAssessment",
    "OptionFeeComponent",
    "OptionFeeDataProvider",
    "OptionFeeEvent",
    "OptionFeeLine",
    "OptionFeeLiquidity",
    "OptionFeeRounding",
    "OptionFeeSchedule",
    "OptionFeeSide",
    "OptionLegExecution",
    "OptionMarginAssessment",
    "OptionMarginDataProvider",
    "OptionMarginPolicy",
    "OptionMarginPosition",
    "OptionMarginRequirementType",
    "OptionMarginScenario",
    "OptionMarginScenarioLoss",
    "OptionMarginScenarioPrice",
    "OptionMarginSnapshot",
    "OptionPackageExecution",
    "OptionPackageExecutionStatus",
    "OptionPackageLeg",
    "OptionPackageMarketStatus",
    "OptionPackageOrder",
    "OptionPackageRejectReason",
    "OptionPackageTimeInForce",
    "OptionQuote",
    "OptionRight",
    "OptionSettlement",
    "OptionSurfaceIntegrityError",
    "OptionSurfaceSnapshot",
    "OptionSurfaceViolation",
    "OptionSurfaceViolationType",
    "OrderBook",
    "OrderBookSource",
    "PaperBroker",
    "PaperFillAudit",
    "PaperPosition",
    "PaperState",
    "RecallInstruction",
    "RecallNotice",
    "RollAction",
    "RollDecision",
    "RollPolicy",
    "RollSnapshot",
    "SettlementStyle",
    "StaticBorrowDataProvider",
    "StaticFinancingDataProvider",
    "StaticMarketStatusProvider",
    "StaticOptionDeliverableDataProvider",
    "StaticOptionFeeDataProvider",
    "StaticOptionMarginDataProvider",
    "WalkedFill",
    "accrue_borrow_charge",
    "accrue_financing",
    "apply_adjusted_assignment",
    "apply_assignment",
    "apply_physical_deliverable",
    "assess_option_lifecycle_fees",
    "assess_option_scenario_margin",
    "assess_option_trade_fees",
    "evaluate_locate",
    "execute_displayed_option_package",
    "execution_block_reason",
    "expiry_adjusted_delivery",
    "expiry_delivery",
    "incremental_short_qty",
    "intrinsic_value",
    "recall_instruction",
    "select_roll",
    "variation_margin",
    "walk_book",
]
